name=Atmega328P-MuxControl
version=1.0.0
author=Aliperti Leonardo <aliperti.leo@gmail.com>
maintainer=Aliperti Leonardo <aliperti.leo@gmail.com>
sentence=A simple, object-oriented library to control analog multiplexers.
paragraph=Like MuxControl.h but optimaized for Atmega328P (nearly 40x faster)
category=Signal Input/Output
url=https://github.com/leoaliperti/Analog-Multiplexer-Arduino-Library
architectures=*
includes=MuxControl.h
