name=MuxControl
version=1.1.0
author=Aliperti Leonardo <aliperti.leo@gmail.com>
maintainer=Aliperti Leonardo <aliperti.leo@gmail.com>
sentence=A simple, object-oriented library to control analog multiplexers.
paragraph=Easily control standard 4-pin multiplexers (like the CD74HC4067) up to 16 channels, or manage custom 8-pin multi-mux setups. Features fast bitwise operations and automatic array population for bulk reading.
category=Signal Input/Output
url=https://github.com/leoaliperti/Analog-Multiplexer-Arduino-Library
architectures=*
includes=MuxControl.h
